name: The Odyssey

on:
  schedule:
    - cron: '5 0,4,8,12,16,20 * * *'  # 4pm, 8pm, midnight, 4am, 8am, noon PST (UTC-8)
  workflow_dispatch:

jobs:
  post-chunk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dactylic-odyssey/requirements.txt

      - name: Post next lines to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.DACTYLIC_ODYSSEY_CHANNEL_ID }}
        run: python dactylic-odyssey/notifier.py
